---
# ConfigMap per il Caddyfile (Caddy fungerà da Ingress Controller)
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    # Blocco per i domini autorizzati
    ciaosonoungattino.giuseppemauro.ovh, ciaosonoungattino.ovh {
        tls giuseppemauro99@gmail.com {
            protocols tls1.2 tls1.3
        }

        # Se la richiesta è per /robots.txt, servila dalla directory statica
        @robots {
            path /robots.txt
        }
        handle @robots {
            root * /usr/share/caddy
            file_server
        }
        
        # Per tutte le altre richieste inoltra al backend
        reverse_proxy ciaosonoungattino-ig-app.ciaosonoungattino-namespace.svc.cluster.local:8390
    }

    # Blocco fallback per ogni altro hostname (TLS disabilitato per evitare certificati wildcard)
    * {
        tls off
        # Gestione speciale per /robots.txt: servilo sempre
        @robots {
            path /robots.txt
        }
        handle @robots {
            root * /usr/share/caddy
            file_server
        }

        # Per tutte le altre richieste restituisci 404
        respond "Not Found" 404
    }
---
# Deployment per Caddy (Ingress Controller)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-ingress
  labels:
    app: caddy-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy-ingress
  template:
    metadata:
      labels:
        app: caddy-ingress
    spec:
      containers:
      - name: caddy
        image: caddy:2
        args: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        # Utilizza emptyDir per i dati temporanei (es. log, cache)
        - name: caddy-data
          mountPath: /data
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config
      - name: caddy-data
        emptyDir: {}
---
# Service per esporre Caddy (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  type: NodePort
  selector:
    app: caddy-ingress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443
